services:
  media_streaming:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media_streaming
    ports:
      - "1935:1935"   # RTMP
      - "8083:8083"   # HTTP HLS
    volumes:
      - ./storage/hls:/hls
      - ./storage/vod:/vod
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge
